apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: demo-danweb

images:
- name: williambr2022/demo-agenda-front
  newName: williambr2022/demo-agenda-front
  newTag: 08148c58fbc89112ca6fadd5798d7f4fd6428f98
