apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: demo-danweb

images:
- name: demo-danweb-front
  newName: williambr2022/demo-danweb-front
  newTag: 9601b7dd062a4f54d47c79ee85affd6689eafb6f