apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: bella-skin

images:
- name: williambr2022/bella-skin-front
  newName: williambr2022/bella-skin-front
  newTag: 41ee25f5776e622dda771fc36c20522f677a42b7
