apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: bella-skin

images:
- name: williambr2022/bella-skin-front
  newName: williambr2022/bella-skin-front
  newTag: a0da69e5551adee311cf0ff8eaafacd97d518b92
