apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: demo-danweb

images:
- name: demo-agenda-front
  newName: williambr2022/demo-agenda-front
  newTag: e217ebc2fc03101803309fef9220e4c56e792024
